// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhbcjjbuyklglpftcbbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYmNqamJ1eWtsZ2xwZnRjYmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTc5ODYsImV4cCI6MjA2NTgzMzk4Nn0.GFoo9XptFAri1Zg-QrOnXG5EFXLV82VcgGwuRjBNHaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);